name: Test application

on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    test:
        name: 'PHP ${{ matrix.php-version }}, Behat Suite ${{ matrix.behat-suite }}, Dependencies ${{ matrix.dependencies }}'
        runs-on: ubuntu-latest

        env:
            SYMFONY_DEPRECATIONS_HELPER: ${{ matrix.symfony-deprecation-helper }}
            BEHAT_SUITE: ${{ matrix.behat-suite }}
            COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        strategy:
            fail-fast: false

            matrix:
                include:


                    - php-version: '8.1'
                      dependencies: highest
                      behat-suite: cli

        steps:
            - name: Checkout project
              uses: actions/checkout@v2

            - name: Install and configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: 'composer:v2'

            - name: Install dependencies with Composer
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependencies }}
                  composer-options: ${{ matrix.composer-options }}

            - name: Start Jackrabbit
              run: |
                wget -nv http://archive.apache.org/dist/jackrabbit/2.21.10/jackrabbit-standalone-2.21.10.jar
                zipinfo jackrabbit-standalone-2.21.10.jar | wc -l
                java -version
                java -jar jackrabbit-standalone-2.21.10.jar
#               JACKRABBIT_VERSION=2.21.10 tests/bin/travis_jackrabbit.sh || java -jar ./vendor/jackalope/jackalope-jackrabbit/bin/jackrabbit-standalone-2.21.10.jar

            - name: Execute test cases
              run: |
                  vendor/bin/phpunit
                  vendor/bin/phpspec run
                  vendor/bin/behat --suite=${{ matrix.behat-suite }}
